### ISSUE TITLE
Saints of Virtue maps require increased limits.

### ISSUE THREAD

**Issue by iliags** [firoball/A3Tools#1]
I tried to convert some maps from an A3 game called Saints of Virtue (game source and initial extraction instructions [here](https://www.youtube.com/watch?v=onP1y6PtBy0)) but it fails to convert the Apathy map because it's too large. The log stops like it hit a limit and gave up ([sysmsg.log](https://github.com/firoball/A3Tools/files/9305452/sysmsg.log)).

I changed the ending from WMP to txt so github would accept it.
[apathy.txt](https://github.com/firoball/A3Tools/files/9305463/apathy.txt)

~5.1k Verts
~1.0k Regions
~5.8k Walls
~600 Things/Actors

**Comment by firoball** [comment]
Hi,
currently I don't have time to further work on this tool, so I cannot provide an immediate fix.

A first guess would be the limit of one of the buffers is hit. You can try adjusting them on your own and see if this helps:

https://github.com/firoball/A3Tools/blob/870259c0098bd839833584a666d8904a0af00526/source/a3conv/a3convmap/makereg.c#L49
Please take note of comments, some of these values need to be factor 3 since they store x/y/z values.

https://github.com/firoball/A3Tools/blob/870259c0098bd839833584a666d8904a0af00526/source/a3conv/a3convmap/makereg.c#L103
Sizes need to be adjusted here as well.

The sizes were selected "just to be big enough", I may have underestimated how big maps became in A3 games :)

**Comment by iliags** [comment]
That's ok, I don't have a copy of A8 and I was just messing around with stuff in the first place; nothing serious.

**Comment by firoball** [comment]
Hi,
somewhat off-topic:
I am currently doing some experimental work on a WDL to C# transpiler.
For doing some testing I am interested in throwing any A3 game against it. Therefore, I'd be interested if you still have any A3 games and are willing to share.

Don't expect this transpiler to produce anything useful (in terms of visuals or even playable) in the next time, though.

Thank you.

**Comment by iliags** [comment]
Saints of Virtue can be acquired from [myabandonware](https://www.myabandonware.com/game/saints-of-virtue-dwo) and someone made a patch for modern systems [here](https://saintsofvirtuex.com/).

**Comment by firoball** [comment]
Thanks a lot for the hint.
In future, when I am back to map loading based on the transpiler I may see why old A3Tools fails with this game. The log file unfortunately does not tell much, since A8 uses buffered file writes. Therefore, it does not tell the exact point of failure. But there is a chance I may find the root cause in future. It will take time, though.

**Comment by firoball** [comment]
Nice site you found there, actually. It also hosts the (even at its time) horrible "Angst" game. 
More stuff for future tests of transpiler :)

https://www.myabandonware.com/game/angst-rahz-s-revenge-bku
